In [ ]:
# # Required installations (run once)
# !brew install wget  # Added by Miles
# !pip install --upgrade --ignore-installed wrapt  # Added by Miles
# !pip install tensorflow==2.0.0-beta0  # Edited by Miles (switch to CPU version)
# !pip install tensorflow_datasets  # Added by Miles

In [4]:
print(tf.__version__)

2.0.0-beta0


In [92]:
import os
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
keras = tf.keras
import tensorflow_datasets as tfds
tfds.disable_progress_bar()
import pymongo        # MongoDB
from PIL import Image
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import numpy as np
from PIL import Image
from io import BytesIO
import boto3

bucket = 'mlw-dsaf'
#key = 

### Data download

### Format the Data

Use the `tf.image` module to format the images for the task.

Resize the images to a fixes input size, and rescale the input channels to a range of `[-1,1]`

<!-- TODO(markdaoust): fix the keras_applications preprocessing functions to work in tf2 -->

---
### _This (below) is used!_

In [6]:
IMG_SIZE = 160 # All images will be resized to 160x160

def prepare_image(image, height=IMG_SIZE, width=IMG_SIZE):
    image = tf.cast(image, tf.float32)
    image = (image/127.5) - 1
    image = tf.image.resize(image, (height, width))
    return image

---

### _Start custom image pull_

In [7]:
!LS

LICENSE                              drivers
README.md                            fast_and_furious.py
__pycache__                          photos_of_ff_cast.ipynb
aws_linked.ipynb                     photos_of_ff_cast_lsm.ipynb
deep_feature_extraction_ff_lsm.ipynb test_data
downloads


In [79]:
# # from os import walk

# f = []
# for dirpath, dirnames, filenames in os.walk('test_data'):
#     print(dirnames)
#     for ff in filenames:
#         curr_path = os.path.join(dirnames, ff)
#         print(curr_path)

# LSM Folder Paths

In [9]:
folder_names = []
for dirpath, dirnames, filenames in os.walk('test_data'):
    folder_names.append(dirnames)

folder_names

[['brian', 'hobbs'], [], []]

In [10]:
file_names = []
for dirpath, dirnames, filenames in os.walk('test_data'):
    file_names.append(filenames)

file_names

[[],
 ['6.paul-walker-medium.jpg',
  '11.2.37830931.jpg',
  '2.paul-walker-21044993-1-402.jpg',
  '9.66892393.jpg',
  '1.maxresdefault.jpg',
  '12.gettyimages-168243951.jpg',
  '5._102791014_gettyimages-164559639.jpg',
  '8.paul-walker.jpg',
  '3.220px-PaulWalkerEdit-1.jpg',
  '4.MV5BMjIwODc0OTk2Nl5BMl5BanBnXkFtZTcwOTQ5MDA0Mg@@._V1_UX214_CR0,0,214,317_AL_.jpg'],
 ['3.dwayne-johnson-11818916-1-402.jpg',
  '5.416x416.jpg',
  '2.MV5BMTkyNDQ3NzAxM15BMl5BanBnXkFtZTgwODIwMTQ0NTE@._V1_.jpg',
  '4.5b462c57f4af9c1a008b45eb-750-563.jpg',
  '8.the-rock-1.jpg',
  '7.190127_3871676_Dwayne__The_Rock__Johnson_Wants_To_Be_In__Cr_800x450_1432791619872.jpg',
  '1.220px-Dwayne_Johnson_2%2C_2013.jpg',
  '9.MV5BODYzNzg4MjAxMF5BMl5BanBnXkFtZTgwNDEyODQ0MzI@._CR792,139,275,275_UX402_UY402._SY201_SX201_AL_.jpg',
  '10.Shutterstock-Dwayne-Johnson-JStone.jpg']]

In [11]:
image_paths = []

In [12]:
for file in file_names[1]:
    image_paths.append('./test_data/' + folder_names[0][0] + '/' + file)

In [13]:
for file in file_names[2]:
    image_paths.append('./test_data/' + folder_names[0][1] + '/' + file)

In [14]:
image_paths

['./test_data/brian/6.paul-walker-medium.jpg',
 './test_data/brian/11.2.37830931.jpg',
 './test_data/brian/2.paul-walker-21044993-1-402.jpg',
 './test_data/brian/9.66892393.jpg',
 './test_data/brian/1.maxresdefault.jpg',
 './test_data/brian/12.gettyimages-168243951.jpg',
 './test_data/brian/5._102791014_gettyimages-164559639.jpg',
 './test_data/brian/8.paul-walker.jpg',
 './test_data/brian/3.220px-PaulWalkerEdit-1.jpg',
 './test_data/brian/4.MV5BMjIwODc0OTk2Nl5BMl5BanBnXkFtZTcwOTQ5MDA0Mg@@._V1_UX214_CR0,0,214,317_AL_.jpg',
 './test_data/hobbs/3.dwayne-johnson-11818916-1-402.jpg',
 './test_data/hobbs/5.416x416.jpg',
 './test_data/hobbs/2.MV5BMTkyNDQ3NzAxM15BMl5BanBnXkFtZTgwODIwMTQ0NTE@._V1_.jpg',
 './test_data/hobbs/4.5b462c57f4af9c1a008b45eb-750-563.jpg',
 './test_data/hobbs/8.the-rock-1.jpg',
 './test_data/hobbs/7.190127_3871676_Dwayne__The_Rock__Johnson_Wants_To_Be_In__Cr_800x450_1432791619872.jpg',
 './test_data/hobbs/1.220px-Dwayne_Johnson_2%2C_2013.jpg',
 './test_data/hobbs/9.MV5B

# End LSM

In [ ]:
# path = '/Users/werlindo/Dropbox/flatiron/projects/mod4_project/downloads/_ready/dwayne_johnson/107.dwayne-johnson.jpg'
# path2 = '/Users/werlindo/Dropbox/flatiron/projects/mod4_project/downloads/_ready/dwayne_johnson/104.intro-1525281779.jpg'


---
### _Get features._

IMG_SHAPE = (IMG_SIZE, IMG_SIZE, 3)

# Create the base model from the pre-trained model MobileNet V2
base_model = tf.keras.applications.MobileNetV2(input_shape=IMG_SHAPE,
                                               include_top=False,
                                               weights='imagenet')

global_average_layer = tf.keras.layers.GlobalAveragePooling2D()

model = tf.keras.Sequential([
  base_model,
  global_average_layer,
])

def extract_features(image):
    """Return a vector of 1280 deep features for image."""
    image_resized = prepare_image(image)
    image_np = image_resized.numpy()
    images_np = np.expand_dims(image_np, axis=0)
    image_np.shape, images_np.shape
    deep_features = model.predict(images_np)
    return deep_features[0]

extract_features(image)

In [90]:
from sklearn.base import BaseEstimator, TransformerMixin

class ImageFeatureExtractor(BaseEstimator, TransformerMixin):
    """Extracts deep features from images."""
    
    def __init__(self, model="MobileNetV2", height=160, width=160):
        """Creates an ImageFeatureExtractor using the specified model."""
        self.height, self.width = height, width
        if model == "MobileNetV2":
            base_model = tf.keras.applications.MobileNetV2(
                input_shape=(height, width, 3),
               include_top=False,
               weights='imagenet'
            )
        else:
            raise Exception("Model unknown")
        global_average_layer = tf.keras.layers.GlobalAveragePooling2D()
        self.model = tf.keras.Sequential([base_model, global_average_layer])
    
    def fit(self, X, y):
        """We're using a pre-trained model, so there's nothing to fit."""
        pass
    
    def transform(self, X):
        """Transforms image file paths into Numpy arrays of deep features."""
        result = []
        for image_pathname in X:
            result.append(self._transform_one(image_pathname))
        print(len(result))
#         return np.array(result)
        return result
    
    def _transform_one(self, image_pathname):
        """Transforms a single image pathname into deep features."""
        img = Image.open(image_pathname)
        img.load()
        image = np.asarray(img)
        return self._extract_features(image)
    
    def _extract_features(self, image):
        """Return a vector of 1280 deep features for image."""
        image_resized = prepare_image(image)
        image_np = image_resized.numpy()
        images_np = np.expand_dims(image_np, axis=0)
        image_np.shape, images_np.shape
        deep_features = self.model.predict(images_np)
        return deep_features[0]
    
    def _prepare_image(self, image):
        """Converts an image to the expected format for prediction."""
        image = tf.cast(image, tf.float32)
        image = (image/127.5) - 1
        image = tf.image.resize(image, (self.height, self.width))
        return image
    
    def fetch_image_from_s3(self, bucket, key):             #Anna's Code
        """Fetches an image from S3 and returns a numpy array."""
        s3 = boto3.client('s3')
        response = s3.get_object(Bucket=bucket, Key=key)
        body = response['Body']
        data = body.read()    
        f = BytesIO(data)
        image = Image.open(f)   
        image_data = np.asarray(image)
        return image_data


### Testing Out Anna's Code

In [95]:
testing = ImageFeatureExtractor()
testing.fetch_image_from_s3(bucket, 'megan/1.missandei-TLOTS-700x500.png')

array([[ 9,  9,  9, ..., 45, 45, 45],
       [ 9,  9,  9, ..., 45,  8, 45],
       [ 9,  9,  2, ..., 45, 45, 45],
       ...,
       [ 0,  0,  0, ..., 56, 48, 63],
       [ 0,  0, 20, ..., 49, 63, 63],
       [ 0,  0,  0, ..., 49, 63, 63]], dtype=uint8)

In [16]:
extractor = ImageFeatureExtractor()

In [17]:
features = extractor.transform(image_paths)

19


In [18]:
!pwd

/Users/laurashummonmaass/Documents/flatiron/mod_4/final_project/mod4_project


In [19]:
features

[array([0.45510256, 0.        , 0.        , ..., 0.41784862, 0.        ,
        0.01271284], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0.07392223, 0.        , 0.00697432, ..., 0.        , 0.        ,
        0.        ], dtype=float32),
 array([0.2498211 , 0.        , 0.17990871, ..., 0.        , 0.        ,
        0.        ], dtype=float32),
 array([0.9305053 , 0.        , 0.83294296, ..., 0.09675258, 0.        ,
        0.        ], dtype=float32),
 array([0.16764668, 0.        , 0.        , ..., 0.00537357, 0.        ,
        0.        ], dtype=float32),
 array([0.01346662, 0.        , 0.39356804, ..., 0.        , 0.        ,
        0.        ], dtype=float32),
 array([0.9367818, 0.2793051, 0.       , ..., 0.       , 0.       ,
        0.       ], dtype=float32),
 array([0.13647854, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ], dtype=float32),
 array([0.12628074, 0.        , 0.00428738, ..., 0.        , 0.        ,

In [21]:
features_dict = dict(zip(image_paths, features))

In [22]:
zippy = list(zip(image_paths,features))

In [23]:
zippy[0][0]

'./test_data/brian/6.paul-walker-medium.jpg'

In [24]:
zippy[0][1]

array([0.45510256, 0.        , 0.        , ..., 0.41784862, 0.        ,
       0.01271284], dtype=float32)

In [25]:
list_of_dicts = [{tup[0]:tup[1]} for tup in zippy]

In [26]:
list_of_dicts

[{'./test_data/brian/6.paul-walker-medium.jpg': array([0.45510256, 0.        , 0.        , ..., 0.41784862, 0.        ,
         0.01271284], dtype=float32)},
 {'./test_data/brian/11.2.37830931.jpg': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)},
 {'./test_data/brian/2.paul-walker-21044993-1-402.jpg': array([0.07392223, 0.        , 0.00697432, ..., 0.        , 0.        ,
         0.        ], dtype=float32)},
 {'./test_data/brian/9.66892393.jpg': array([0.2498211 , 0.        , 0.17990871, ..., 0.        , 0.        ,
         0.        ], dtype=float32)},
 {'./test_data/brian/1.maxresdefault.jpg': array([0.9305053 , 0.        , 0.83294296, ..., 0.09675258, 0.        ,
         0.        ], dtype=float32)},
 {'./test_data/brian/12.gettyimages-168243951.jpg': array([0.16764668, 0.        , 0.        , ..., 0.00537357, 0.        ,
         0.        ], dtype=float32)},
 {'./test_data/brian/5._102791014_gettyimages-164559639.jpg': array([0.01346662, 0.        , 0.39356804, ..., 0. 

In [27]:
features_dict

{'./test_data/brian/6.paul-walker-medium.jpg': array([0.45510256, 0.        , 0.        , ..., 0.41784862, 0.        ,
        0.01271284], dtype=float32),
 './test_data/brian/11.2.37830931.jpg': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 './test_data/brian/2.paul-walker-21044993-1-402.jpg': array([0.07392223, 0.        , 0.00697432, ..., 0.        , 0.        ,
        0.        ], dtype=float32),
 './test_data/brian/9.66892393.jpg': array([0.2498211 , 0.        , 0.17990871, ..., 0.        , 0.        ,
        0.        ], dtype=float32),
 './test_data/brian/1.maxresdefault.jpg': array([0.9305053 , 0.        , 0.83294296, ..., 0.09675258, 0.        ,
        0.        ], dtype=float32),
 './test_data/brian/12.gettyimages-168243951.jpg': array([0.16764668, 0.        , 0.        , ..., 0.00537357, 0.        ,
        0.        ], dtype=float32),
 './test_data/brian/5._102791014_gettyimages-164559639.jpg': array([0.01346662, 0.        , 0.39356804, ..., 0.        , 0.       

# LSM Random Forests

In [53]:
target = ['brian', 'brian', 'brian', 'brian', 'brian', 'brian', 'brian', 'brian', 'brian', 'brian', 
          'hobbs', 'hobbs', 'hobbs', 'hobbs', 'hobbs', 'hobbs', 'hobbs', 'hobbs', 'hobbs']

In [54]:
X_train, X_test, y_train, y_test = train_test_split(features, 
                                                    target, 
                                                    test_size = 0.25,
                                                    random_state=123)

### Regular Tree

In [65]:
tree_clf = DecisionTreeClassifier(criterion = "gini", max_depth = 5) 
tree_clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=5,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [58]:
tree_clf.feature_importances_

array([0., 0., 0., ..., 0., 0., 0.])

In [64]:
pred = tree_clf.predict(X_test)
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[1 2]
 [0 2]]
              precision    recall  f1-score   support

       brian       1.00      0.33      0.50         3
       hobbs       0.50      1.00      0.67         2

   micro avg       0.60      0.60      0.60         5
   macro avg       0.75      0.67      0.58         5
weighted avg       0.80      0.60      0.57         5



### Random Forest

In [75]:
forest = RandomForestClassifier(n_estimators=20, max_depth= 5)
forest.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=5, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [76]:
forest.score(X_train, y_train)

1.0

In [78]:
forest.score(X_test, y_test)

1.0

#### This is likely not right.... 

# End LSM

In [29]:
# Set up connection string
mongo_user = 'werlindo'
mongo_pw = 'dsaf040119'

In [30]:
# Instantiate client
client = pymongo.MongoClient("mongodb+srv://" + mongo_user + ":" 
                         + mongo_pw 
                         + "@dsaf-oy1s0.mongodb.net/test?retryWrites=true")


ConfigurationError: The "dnspython" module must be installed to use mongodb+srv:// URIs

In [ ]:
#cli = pymongo.MongoClient('mongodb+srv://werlindo:dsaf040119@dsaf-oy1s0.mongodb.net/test?retryWrites=true')

In [ ]:
db = client['furious']
coll = db['images']

In [ ]:
coll.delete_many({})

In [ ]:
coll.insert_many(list_of_dicts, bypass_document_validation=True)

In [ ]:
# Look at DB names
cur = client.list_databases()

for item in cur:
    print(item)

In [ ]:
# Look at everything in our collection!
cur = coll.find({})

for item in cur:
    print(item)

# graveyard

----
### _We can do train / test split before we push through classification models?_

In [ ]:
train_images = [(img.numpy(), label.numpy())
                for (img, label) in raw_train.take(10000)]

In [ ]:
test_images = [(img.numpy(), label.numpy())
               for (img, label) in raw_test.take(1000)]

In [ ]:
plt.imshow(train_images[0][0])
plt.title(get_label_name(train_images[0][1]))

In [ ]:
train_X_img, train_y = zip(*train_images)
test_X_img, test_y = zip(*test_images)

# Extract features from some images

In [ ]:
TRAIN_LIMIT = 1000
TEST_LIMIT = 200

In [ ]:
train_X_small = [extract_features(img)
                 for img in train_X_img[:TRAIN_LIMIT]]
test_X_small = [extract_features(img)
                for img in test_X_img[:TEST_LIMIT]]

In [ ]:
train_y_small = train_y[:TRAIN_LIMIT]
test_y_small = test_y[:TEST_LIMIT]

# Logistic Regression on Deep Features

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(solver='lbfgs')
lr.fit(train_X_small, train_y_small)

In [ ]:
train_preds = lr.predict(train_X_small)
(sum(train_y_small) / len(train_y_small),
 sum(train_preds == train_y_small) / len(train_y_small))

In [ ]:
test_preds = lr.predict(test_X_small)
(sum(test_y_small) / len(test_y_small),
 sum(test_preds == test_y_small) / len(test_y_small))

In [ ]:
idxs=np.argsort(np.abs(lr.coef_[0]))[::-1]

In [ ]:
plt.hist(lr.coef_[0])

In [ ]:
import pandas as pd
pd.DataFrame({'values': lr.coef_[0][idxs], 'idx': idxs})

# Random Forest on Deep Features

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=1000, n_jobs=-1)
rfc.fit(train_X_small, train_y_small)

In [ ]:
train_preds = rfc.predict(train_X_small)
(sum(train_y_small) / len(train_y_small),
 sum(train_preds == train_y_small) / len(train_y_small))

In [ ]:
test_df = pd.DataFrame(test_X_small)

In [ ]:
test_df.head()

In [ ]:
test_preds = rfc.predict(test_X_small)
(sum(test_y_small) / len(test_y_small),
 sum(test_preds == test_y_small) / len(test_y_small))

In [ ]:
rf_idxs = np.argsort(rfc.feature_importances_)[::-1]

In [ ]:
rf_idxs

In [ ]:
rfc.feature_importances_[rf_idxs]

In [ ]:
permuted_test_df = test_df.copy()
idx_list = rf_idxs[:10]
for idx in idx_list:
    important_feature = test_df.loc[:, idx].copy().values
    np.random.shuffle(important_feature)
    permuted_test_df.loc[:, idx] = important_feature

In [ ]:
test_preds = rfc.predict(permuted_test_df)
(sum(test_y_small) / len(test_y_small),
 sum(test_preds == test_y_small) / len(test_y_small))